config/routes.rb
Rails.application.routes.draw do
  apipie
  namespace :api do
    namespace :v1 do
      resources :devices, only: [:create] do
        resources :measures, only: [:create]
      end
    end
  end

  resources :devices, only: [:index] do
    resources :measures, only: [:index]
  end

  resources :notifications, only: [:update]
  
  resources :sessions, only: [:new, :create, :destroy]

  root 'devices#index'
end

app/models/api_client.rb
class ApiClient < ApplicationRecord
  validates :token, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :measures

  validates :firmware_version,
            format: Constants::SEMVER_REGEX,
            presence: true

  validates :serial_number,
            presence: true,
            uniqueness: true

  def measures_with_unread_notifications
    measures.joins(:notifications).merge(Notification.unreads)
  end

  def to_h
    self.slice(:id, :serial_number, :firmware_version)
    .merge({
      registered_at: self.created_at
    })
  end
end

app/models/measure.rb
class Measure < ApplicationRecord
  WARNING_STATUS = ['needs_service', 'needs_new_filter', 'gas_leak'].freeze
  CARBON_MONOXIDE_LIMIT = 9

  belongs_to :device

  has_many :notifications

  validates :air_humidity,
              presence: true,
              numericality: true

  validates :carbon_monoxide,
              presence: true,
              numericality: true

  validates :health_status,
              presence: true,
              length: { maximum: 150 }

  validates :temperature,
              presence: true,
              numericality: true

  def notificable?
     not_healthy? || hight_carbon_monoxide?
  end

  def not_healthy?
    WARNING_STATUS.include?(self.health_status)
  end

  def hight_carbon_monoxide?
    self.carbon_monoxide > CARBON_MONOXIDE_LIMIT
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :measure

  scope :unreads, -> { where(read: false) }

  def self.with_measure_and_device
    eager_load(measure: [:device])
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_cors
  before_action :authenticate_client

  private

  def set_cors
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

  def authenticate_client
    client_token = request.headers['HTTP_API_TOKEN']
    unless ApiClient.exists?(token: client_token)
      return render json: {}, status: :unauthorized
    end
  end
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::BaseController
  include DevicesDocs

  def create
    device = Device.new(device_params)

    if device.save
      render json: device.to_h, status: :ok
    else
      render json: {
        error: device.errors.full_messages.shift
      }, status: :unprocessable_entity
    end
  end

  private
  def device_params
    params.permit(:serial_number, :firmware_version)
  end
end

app/controllers/api/v1/measures_controller.rb
class Api::V1::MeasuresController < Api::V1::BaseController
  include MeasuresDoc 
  before_action :find_device

  def create
    measures = Measures::Creator.for(measure_params, @device)
    if measures.succuess?
      render json: { success: true }, status: :ok
    else
      render json: {
        success: false,
        error: measures.error
      }, status: :unprocessable_entity
    end
  end

  private

  def find_device
    @device = Device.find(params[:device_id])
  end

  def measure_params
    request.parameters[:_json]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :active_notifications

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def active_notifications
    Notification.unreads.with_measure_and_device
  end

  def authenticate
    redirect_to new_session_path if current_user.nil?
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate

  def index
    @devices = Device.all
  end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :authenticate
  before_action :find_device

  def index
    @measures = Measures::Filter.new(params, @device)
  end

  private

  def find_device
    @device = Device.find(params[:device_id])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate

  def update
    notification = Notification.find(params[:id])
    notification.update(read: true)

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_notification_message(notification)
    issues = []
    issues << 'a value of Carbon Monoxide of over 9 PPM' if notification.measure.hight_carbon_monoxide?
    issues << "a health status of #{notification.measure.health_status}" if notification.measure.not_healthy?
    issues.to_sentence
  end
end

app/views/devices/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card table-container my-5">
        <h2 class="text-center">Registered devices</h2>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Serial number</th>
                  <th scope="col">Firmware version</th>
                  <th scope="col">Registration date</th>
                  <th scope="col-1"></th>
                </tr>
              </thead>
              <tbody>
                <% @devices.each do |device| %>
                  <tr>
                    <td><%= device.serial_number %></td>
                    <td><%= device.firmware_version %></td>
                    <td><%= I18n.localize device.created_at, format: :long %></td>
                    <td><%= link_to "See sensors", device_measures_path(device) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart AC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Smart AC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <% unless current_user.nil? %>
            <ul class="navbar-nav mr-auto">
            </ul>

            <ul class="navbar-nav">
              <li class="nav-item active">
                <%= link_to 'Log out', session_path(current_user), method: :delete, class: 'nav-link' %>
              </li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <main>
      <% unless current_user.nil? %>
        <%= render partial: 'partials/notification', locals: { notifications: active_notifications }%>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/measures/index.html.erb
<div class="measures-container">
  <div class="my-5">
    <%= link_to 'Go back', devices_path, class: 'btn btn-primary' %>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card table-container">
        <div class="card-body">
          <h2 class="text-center">Device Information</h2>
          <div class="table-responsive my-5">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Serial number</th>
                  <th scope="col">Firmware version</th>
                  <th scope="col">Registration date</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @device.serial_number %></td>
                  <td><%= @device.firmware_version %></td>
                  <td><%= I18n.localize @device.created_at, format: :long %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4 mx-auto">
      <div class="card table-container my-5">
        <div class="card-body">
          <h4 class="text-center">Temperature</h4>
          <%= line_chart @measures.temperature %>
          <div class="my-5">
            <%= form_with(local: true, url: device_measures_path(@device), class: 'form-inline', method: :get) do |f| %>
              <div class="form-group">
                <%= f.select('filter[temperature]', Measures::Filter.filters_collection, { selected: params.dig(:filter, :temperature) }, class: 'form-control filter-select')%>
                <%= f.hidden_field 'filter[air_humidity]', value: params.dig(:filter, :air_humidity) %>
                <%= f.hidden_field 'filter[carbon_monoxide]', value: params.dig(:filter, :carbon_monoxide) %>
                <button type="submit" class="btn btn-primary">Filter</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 mx-auto">
      <div class="card table-container my-5">
        <div class="card-body">
          <h4 class="text-center">Air humidity</h4>
          <%= line_chart @measures.air_humidity %>
          <div class="my-5">
            <%= form_with(local: true, url: device_measures_path(@device), class: 'form-inline', method: :get) do |f| %>
              <div class="form-group">
                <%= f.select('filter[air_humidity]', Measures::Filter.filters_collection, { selected: params.dig(:filter, :air_humidity) }, class: 'form-control filter-select')%>
                <%= f.hidden_field 'filter[temperature]', value: params.dig(:filter, :temperature) %>
                <%= f.hidden_field 'filter[carbon_monoxide]', value: params.dig(:filter, :carbon_monoxide) %>
                <button type="submit" class="btn btn-primary">Filter</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 mx-auto">
      <div class="card table-container my-5">
        <div class="card-body">
          <h4 class="text-center">Carbon Monoxide</h4>
          <%= line_chart @measures.carbon_monoxide %>
          <div class="my-5">
            <%= form_with(local: true, url: device_measures_path(@device), class: 'form-inline', method: :get) do |f| %>
              <div class="form-group">
                <%= f.select('filter[carbon_monoxide]', Measures::Filter.filters_collection, { selected: params.dig(:filter, :carbon_monoxide) }, class: 'form-control filter-select')%>
                <%= f.hidden_field 'filter[air_humidity]', value: params.dig(:filter, :air_humidity) %>
                <%= f.hidden_field 'filter[temperature]', value: params.dig(:filter, :temperature) %>
                <button type="submit" class="btn btn-primary">Filter</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_notification.html.erb
<% notifications.each  do |notification|%>
  <div class="alert alert-warning" role="alert">
    <p>Device <%= link_to "##{notification.measure.device.serial_number}", device_measures_path(notification.measure.device) %> reported <%= friendly_notification_message(notification) %></p>
    <%= link_to 'Mark as resolved', notification_path(notification), method: :put, class: 'btn btn-primary' %>
  </div>
<% end %>